services:
    ai-jupyter:
        image: ai-jupyter
        hostname: ai-jupyter
        container_name: ai-jupyter
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/home/jovyan/src
        ports:
            - 8888:8888
        command: "start-notebook.sh --NotebookApp.token="